### ISSUE TITLE
Edit page alignment on using text box

### ISSUE THREAD

**Issue by raashika03** [edamontology/edam-browser#103]
On propose change pages,  text is not aligned properly. When we use text box. 

![Screenshot_2021-04-10-15-42-57-51](https://user-images.githubusercontent.com/45493793/114266395-c976e300-9a13-11eb-8d82-65e0ff395744.png)

![Screenshot_2021-04-10-15-50-02-30](https://user-images.githubusercontent.com/45493793/114266556-849f7c00-9a14-11eb-9bea-cc8dc966c32d.png)

While this's ok for main page at least, but search bar isn't aligned as I addressed in other issue.

![Screenshot_2021-04-10-15-47-32-70](https://user-images.githubusercontent.com/45493793/114266469-2b374d00-9a14-11eb-82ab-85b53b3662bb.png)

Should any changes be made? For alignment.

Attributes name are also not visible. So this thing also,  should I address?

**Comment by raashika03** [comment]
Overall this page should be aligned while using search box. This seems better to me. Because right now you can move that page right left after using search text box,  which isn't appealing from user experience point of view.

**Comment by raashika03** [comment]
![Screenshot_2021-04-10-16-16-53-74](https://user-images.githubusercontent.com/45493793/114267284-41470c80-9a18-11eb-8d6d-111d6de72953.png)
  

At least something like this can be done. 
What changes do you suggest @bryan-brancotte @matuskalas @hmenager

**Comment by bryan-brancotte** [comment]
Maybe looking at bootstrap doc to see how they recommend to use horizontal form ?

**Comment by raashika03** [comment]
Yes @bryan-brancotte now I'll see this issue. was waiting for it's approval :sweat_smile: thank you

**Comment by bryan-brancotte** [comment]
Ok, assiging you
