### ISSUE TITLE
ctrl+z for "+" option on propose change pages

### ISSUE THREAD

**Issue by raashika03** [edamontology/edam-browser#104]
![Screenshot_2021-04-10-15-56-27-01](https://user-images.githubusercontent.com/45493793/114266734-77cf5800-9a15-11eb-9690-6e74da92c12e.png)

Will adding a "-" button inside those text box which appears after using "+" button be a good feature, for better user experience.

To be used for collapsing those text boxes,  when the user decides later(after using "+" button) to not add any thing inside that. 

There should be a go back for every action in short. (that too easily for enhancing user experience)

It's like ctrl+z functionality for "+" button.

**Comment by bryan-brancotte** [comment]
Adding a `-` would be more user friendly I agree, but removing the content achieve the same goal. I don't think adding that the benefit justifies the cost.

**Comment by raashika03** [comment]
Ok I agree it wasn't so much useful. It was just for reverting the addition of another input box. 
Thank you :)
