### ISSUE TITLE
Propose changing the mouse cursor to a hand when moving the tree around

### ISSUE THREAD

**Issue by kellydoleo** [edamontology/edam-browser#105]
@matuskalas @hmenager @bryan-brancotte It could be useful to have a hand cursor icon when interacting with the tree instead of the mouse cursor to alert the user that they're able to pull and push the tree around. When hovering over the nodes on the tree, a pointer cursor appears, but outside of that there is only the mouse cursor. 

Would having a hand/grabbing cursor be more helpful instead?

**Comment by bryan-brancotte** [comment]
I though it had already been done, but I was wrong :(, go ahead if you want :)

**Comment by bryan-brancotte** [comment]
Hi, surprisingly the grab cursor does not work on chrome88+ubuntu while working with firefox87+ubuntu.
This issue could also be inderticly solved by #69

**Comment by HagerDakroury** [comment]
@bryan-brancotte should that be still done for browsers supporting it? I think the grab cursor would still be a valuable enhancment

**Comment by bryan-brancotte** [comment]
Yes, why not
