### ISSUE TITLE
speed optimization for Edam browser

### ISSUE THREAD

**Issue by raashika03** [edamontology/edam-browser#110]
Speed matters when it comes to user experience.

Most of the people browse through a website in their smart phones. And the tree map and term details panel takes a bit more time than expected, can anything be done to improve the user experience.
In larger screens like in desktop loading isn't so slow.
As per I researched the major reason for website to be slow are images which load once when that website is accessed, compressing images before uploading them is an option but I don't see any image here, only data to be used for displayed in the term details table and for the creation of tree map is present.
So, can data retrieval for term details panel and tree map be speed up? by any means.

**Comment by raashika03** [comment]
What can be the probable reason for this issue? I got some reasons [here](https://www.altexsoft.com/blog/engineering/12-techniques-of-website-speed-optimization-performance-testing-and-improvement-practices/)
But unable to figure out the exact cause.

**Comment by raashika03** [comment]
As per you said @bryan-brancotte mobile phones ain't our focus (only 5% traffic) so This's not so useful. So I should close this? Please close it. If I'm correct.

**Comment by bryan-brancotte** [comment]
Indeed this issue can be closed.

Note that if performance could be improved, I think not only smartphone should benefit the improvement, but all devices. If you have implementation improving the speed, feel free to PR.

**Comment by raashika03** [comment]
I'll surely look for ways to improve the speed. Thank you.

**Comment by bryan-brancotte** [comment]
Closed as inactive for a long time
