### ISSUE TITLE
Remove 'previously seen' title when not required!

### ISSUE THREAD

**Issue by secrashi** [edamontology/edam-browser#114]
When the website loads, initially, the previously seen field is empty, as shown in the figure!

![WhatsApp Image 2021-04-13 at 12 00 04 PM](https://user-images.githubusercontent.com/56053777/114507456-c583d480-9c50-11eb-9f4f-a67126aeccdb.jpeg)

Proposed solution: We can remove the 'previously seen' title when previously seen terms are 0. 
Can @bryan-brancotte @matuskalas @hmenager approve this, so I'll make a PR for this soon?

**Comment by bryan-brancotte** [comment]
Well spotted, it is a very easy `good first issue`, but go ahead if you want
