### ISSUE TITLE
Resolve conflicting tree event listeners

### ISSUE THREAD

**Issue by HagerDakroury** [edamontology/edam-browser#117]
I came across this when I was testing the tree zooming.
This may be rarely reproduced by users, but worth looking at nonetheless.

When you double click on a node, 2 events are triggered (zooming and expanding the node) which leads to one not being completed (expand)

![conflictingEvents](https://user-images.githubusercontent.com/37930475/114580739-69847480-9c7f-11eb-90bf-645c4b759b85.gif)

**Comment by HagerDakroury** [comment]
Hi @bryan-brancotte, I'm trying to work on this one. I've tried to prevent double zooming ( or any further event for that matter) when clicking on a node.
This is my code inside the click event listener
`d3.event.stopPropagation();
svg.on("dblclick.zoom", null );`

But still, a second click on the node is triggered!

![treeconflicting](https://user-images.githubusercontent.com/37930475/119818397-6e2f8000-beef-11eb-98c0-fb9380ae23a0.gif)

Any direction here? I first though it was due to the double zooming being triggered but looks like it's another issue

**Comment by bryan-brancotte** [comment]
Hi @HagerDakroury 

I don't know how to prevent double zoom/double click, but I might have a lead:
```diff
diff --git a/js/tree-reusable-d3.js b/js/tree-reusable-d3.js
index 5fb9199..1f4e7b5 100644
--- a/js/tree-reusable-d3.js
+++ b/js/tree-reusable-d3.js
@@ -328,6 +328,7 @@ function interactive_tree() {
 
     //Handle selection of a node
     function handleClick(d){
+        console.log(d3.event.detail);
         if (d3.event.shiftKey && use_shift_to_open ||
             d3.event.ctrlKey  && use_control_to_open ||
             d3.event.altKey   && use_alt_to_open){
@@ -343,7 +344,7 @@ function interactive_tree() {
                 //adding ?
                 attemptToSelectElement(d);
             }
-        }else if (!d3.event.shiftKey && !d3.event.ctrlKey && !d3.event.altKey){
+        }else if (!d3.event.shiftKey && !d3.event.ctrlKey && !d3.event.altKey && d3.event.detail == 1){
             chart.cmd.clearSelectedElements(false);
             toggle(d);
             clickedElementHandler(d);
```
it seems that in `d3.event.detail` we have the id of the click when doing multiple click (double, tripple also). First test indicate that it prevent the bug of having the path rendered without the node or text. Indeed it prevent a second call to `toggle` while the animation of the first is still ongoing. It does not prevent the zoom as the zoom event is triggered I don't know where when doing a double click. 

Maybe in the zoom event you could prevent using the `vis.attr("transform", d3.event.transform);` when the event is triggered by/in a node and not the `svg`/`g` ? I don't know how though.

**Comment by HagerDakroury** [comment]
> 
> It seems that in `d3.event.detail` we have the id of the click when doing multiple click (double, tripple also). First test indicate that it prevents the bug of having the path rendered without the node or text. Indeed it prevents a second call to `toggle` while the animation of the first is still ongoing. It does not prevent the zoom as the zoom event is triggered I don't know where when doing a double click.
> 

This is super helpful! I'll proceed trying this out

> Maybe in the zoom event you could prevent using the `vis.attr("transform", d3.event.transform);` when the event is triggered by/in a node and not the `svg`/`g` ? I don't know how though.

I found a function called `zoom.filter` where you can pass events to display zooming at. Just need to get the exact event name when clicking a node and it should take care of that.

Will look into that after handling the double clicking.
Thanks!
