### ISSUE TITLE
Add start script to package.json file

### ISSUE THREAD

**Issue by sunny775** [edamontology/edam-browser#121]
Currently, the instructions for running EDAM browser locally has us start the browser by executing the bash file directly on the shell, as highlighted by the image below
![Screenshot from 2021-04-15 17-02-54](https://user-images.githubusercontent.com/49409497/114901955-3b349f80-9e0d-11eb-94ac-70a2bd77df88.png)
I feel it will be better to have a conventional start script in package.json file, which in turn executes our start bash file.
Something like:  `
. . .
"scripts": {
    "start": "sh start_edam_stand_alone_browser.sh",
    "test": "jshint js/*js"
  },
. . . 
`
That will be much like what everyone is used to

**Comment by sunny775** [comment]
Hi @bryan-brancotte @hmenager  . I'll make a pull request for this if you deem it worthwhile

**Comment by tawahpeggy** [comment]
I think it's a great idea, as when I finished cloning the project the first place I thought of looking for a start script was package.json but it carried no info as such which made me waste some time asking on the private chat group and waiting for people to help me.

**Comment by sunny775** [comment]
Thanks @tawahpeggy

**Comment by bryan-brancotte** [comment]
Thanks for #122 and #123 ! As tawahpeggy indicated it will help futur onboarding users.

I think it could be improved even more: `start_edam_stand_alone_browser.sh` is a custom start script with no reason to exists if we can do completly without it in `package.json` (including opening the windows). I you want, you can propose an alternative that in the end remove `start_edam_stand_alone_browser.sh`.

**Comment by sunny775** [comment]
Thanks a lot @bryan-brancotte . I will work on it :)
