### ISSUE TITLE
Update README.md with platform-specific start instructions

### ISSUE THREAD

**Issue by sunny775** [edamontology/edam-browser#123]
This issue is to update README.md for two reasons:
( 1 )  To include the changes proposed by pull #122 if approved
( 2 ) To add  extra start instruction for windows users.  The current instruction for starting EDAM browser locally doesn't favour windows users, since windows cannot execute bash files directly.  A specific instruction on how to launch the browser locally on Windows OS needs to be added to README.md

**Comment by sunny775** [comment]
Hi @bryan-brancotte  @hmenager  . I'll make a pull request for this if you deem it worthwhile

**Comment by matuskalas** [comment]
I totally support the idea of adding the info potentially needed for Windows users 👍🏽 It has also been noted a couple of times on https://gitter.im/edamontology/edam-browser

**Comment by sunny775** [comment]
Thanks @matuskalas 
I've updated PR #124 to include more detailed platform friendly start options

**Comment by bryan-brancotte** [comment]
Hi @sunny775 good idea ! And also thanks for the help for windows users :clap: :+1: 
Closing as merge
