### ISSUE TITLE
Add a feature to open tree on Full screen!

### ISSUE THREAD

**Issue by secrashi** [edamontology/edam-browser#126]
Currently, a user has to scroll left-right and up-down using a mouse for viewing the whole tree. 
**Proposed solution:** _We can add a new feature where a user can open the tree on full screen, by clicking on a button.
The button can be placed right next to other buttons as marked in the figure._

![WhatsApp Image 2021-04-16 at 11 41 20 AM](https://user-images.githubusercontent.com/56053777/114979895-40472c80-9ea9-11eb-817d-abf42b0d8040.jpeg)

- This solution will remove the need for scrollbars.
- It'll simplify the navigation across different sub-branches of the tree thus enhancing user experience.

Can @bryan-brancotte @matuskalas @hmenager approve this, so I'll make a PR for this soon!

**Comment by hmenager** [comment]
I think this would be a neat feature, please feel free to propose a PR @secrashi !

**Comment by secrashi** [comment]
Sure, thank you!

**Comment by bryan-brancotte** [comment]
Hi @secrashi 

It's a nice feature which open a new possibility for futur evolution of the browser, merging it

**Comment by secrashi** [comment]
Thanks, @bryan-brancotte!

**Comment by secrashi** [comment]
Closing with #141!
