### ISSUE TITLE
Porting EDAM browser source to React js

### ISSUE THREAD

**Issue by sunny775** [edamontology/edam-browser#127]
The project description informs the need to scale the code base to include components for more complex visualizations such as **comparism of different versions of the ontology**.
Hence, the code base needs to be more scalable and maintainable.
With the project we currently have, including these needed features will entail adding more markup to the index.html file and adding more javascript to the javascript files, some of which are already growing out of maintainable proportions.

At this stage, a modular single page application framework like ReactJS will be super handy.
Refactoring the project to React will make it a very modularized web app, with each component scoping it's own javascript and css, making it a pleasure to maintain, scale and debug.
React will also make it very easy to implement optimization techniques like tree-shaking, code-splitting and lazy-loading.
Also, with React, both intergration and unit testing will be painless,and setting up CI / CD to run tests will be pretty straight forward.
React will also make it easier for component re-usability, implementing version comparism for instance will just be a matter of rendering the same tree component with version-specific JSON payload.
Managing the app state will be more fun, implementing cool features like dark mode will just be a matter of setting a state value with defaults which are automatically recieved by all components.

**Comment by sunny775** [comment]
@matuskalas  @bryan-brancotte  @hmenager If you'd deem this worthwhile , which I pray you do, I can get started with it immediately and make a PR for it in 5 - 7 days.

**Comment by bryan-brancotte** [comment]
Hi @sunny775 

You raise a very interesting point on why not using a framework (ReactJS, VueJS, ...). This is currently not the case as skill were not there at the time (2018). 

You points are good, I have one questions: Would it be compatible with github pages ? If not it would be a major drawback as the current github pages hosting solution allows us to have free hosting, even for forks.

Note that doing the refactoring to ReactJS is out of the scope of the outreachy selection phase as it represent too much work.

**Comment by sunny775** [comment]
Yes @bryan-brancotte , it will be absolutely compartible with ReactJS
I understand that it's out of the scope for Outreacy, but I'd love to work on it in my free time.
It will mean every bit of enhancement  envisaged for the project.

**Comment by HagerDakroury** [comment]
@bryan-brancotte any updates if this is feasible right now?

**Comment by bryan-brancotte** [comment]
Laaate answer, sorry

Thanks for your enthusiasm, but I have to decline the migration to react as skills to then maintain it in the futur are not available for now and are not in the scope of next-to-acquire skills
