### ISSUE TITLE
[new feature] Add Authentication

### ISSUE THREAD

**Issue by tawahpeggy** [edamontology/edam-browser#130]
hello Everyone, this is a suggestion I thought of when I was going through the code base. it will be good for users to be tracked in a wise way. not forcing people to create accounts but hiding some complex functionalities like maybe loading between different ontologies just for logged-in users as it will enable us to track how many people we impact and at what time hence enabling us to make concrete decisions on great functionalities to add to the ontology

**Comment by tawahpeggy** [comment]
the tools i suggest to be used include:
node.js
html
css
mongodb as database 
bootstrap etc

**Comment by tawahpeggy** [comment]
i really think tracking users is going to do alot of good especially on getting user feedback and so on

**Comment by bryan-brancotte** [comment]
Hi @tawahpeggy having a db is incompatible with the current hosting strategy: we are using github pages which is equivalent of running an nginx/apache server and nothing else. I am thus closing it as authentication would be a part of a whole new version of the softwear which is not in the current scope of futur feature. Anyhow thanks for the ideas you provide in this issue and the others :)
