### ISSUE TITLE
Allow user to provide feeback

### ISSUE THREAD

**Issue by tawahpeggy** [edamontology/edam-browser#131]
it will be wonderful if we can get user feedback on how to improve the browser and also know what it is that's not done the right way, hence a feedback collection form will be needed

**Comment by tawahpeggy** [comment]
A suggested model will be 
Name:
email:
message:

**Comment by bryan-brancotte** [comment]
Hi @tawahpeggy, thanks for the idea ! Users already "have" a feedback form, it is the github issue system. I agree that it is not that accessible, but better than nothing. I think we should help users creating an issue with a feedback in order to keep all communication/issues/feedback in one place. We could add a link that prefill an issue with information https://docs.github.com/en/github/managing-your-work-on-github/about-automation-for-issues-and-pull-requests-with-query-parameters maybe also create an issue template for feedback (and template for non-feedback issues).

**Comment by tawahpeggy** [comment]
Okay @bryan-brancotte. Thanks for your reply.
I'll do as you have said though I am not sure for how long this solution will be used.The main problem here is not having a server space for user data,isn't it possible to maybe use the same API that the ontology it self uses for this things?
Because I think being dependent on github for so many things, what if it crashes 😅 or is down? Just saying.

**Comment by tawahpeggy** [comment]
I know how to code in node.js  and will be able to implement that fast.
 Never the less I will continue with the feedback on github as you have said for now .🙏🙏

**Comment by bryan-brancotte** [comment]
Hi @tawahpeggy 

Indeed Github can crash, but I am more confident that It will be back online quickly with the millions of user using it than a server self-managed to host a project with less than an hundred users. Also having an application with storage and backend means more dependencies, handling  [GDPR compliance](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation), more work for maintaining the app, more work for maintaining the server or paying the server maintenance, and paying for the server itself. So in the end, as long as a github pages is enough it should be kept and use the free time to work on fun thing, not `apt-get update` and `npm update` ;)

I did not understood what api you are talking about, the ontology is stored in json, and loaded on startup, no API call.

**Comment by tawahpeggy** [comment]
That's true @bryan-brancotte. Your explanation is clear enough and indeed true.🙏🙏
Also,thanks for the clarification on API too.

**Comment by tawahpeggy** [comment]
Hi @bryan-brancotte.
I tried creating the issue template for the feedback as we discussed, but it seems I don't have the right permissions to carry out this action.
Here is a screenshot of how the page appears
![Screenshot from 2021-05-01 12-48-35](https://user-images.githubusercontent.com/40355086/116789285-24808080-aa7c-11eb-8244-d23a0b3d0ab3.png)
here is also a screenshot of one of my personal repository:
![Screenshot from 2021-05-01 12-49-54](https://user-images.githubusercontent.com/40355086/116789465-f2235300-aa7c-11eb-81d8-eee754a79bca.png)

**Comment by bryan-brancotte** [comment]
Hi, indeed you cannot configure the project directly, but you can still create PR with new templates as it is/was carried in https://github.com/edamontology/edamontology/pull/626

**Comment by tawahpeggy** [comment]
okay @bryan-brancotte thanks alot

**Comment by bryan-brancotte** [comment]
Hi @tawahpeggy 

Thanks for your proposition with #183, I have various remarks : 
 * we are asking for the email in a public issue, the email will then be visible to everyone. We shouldn't ask it, and after all we know the author
 * as we know the author, we don't need its name, it is already stated in the github account
 * Having rating is only relevant when in an app store to compare, here it would only be very short summary of the feedback and I would rather have a textual feedback, to work with it and improve the tools.
 * Device is a good idea ! Adding it also to bug template
