### ISSUE TITLE
[good first issue] Remove Some CDNs

### ISSUE THREAD

**Issue by tawahpeggy** [edamontology/edam-browser#132]
During the time I have been studying and also advice from seniors in the field, I have learnt that cdns are good as they make the process easy but they have more disadvantages as a CDN could break at any time and also the company hosting the cdn might decide to change something about it and hence it affects everyone using it and changes will need to be done everywhere. for our case in index.html,edit.html etc hence causing changes and the application may not work properly at the time to.

So a better approach will be to download and install bootstrap,jquery,fontawesome  etc in the application. if you are sceptical because of the app increasing in size a way around that is removing the things in each installation you don't need, eg: if in bootstrap you only need bootstrap.min.js and bootstrap.min.css all others can be removed and just the two left in the folder structure.

**Comment by bryan-brancotte** [comment]
Hi @tawahpeggy , I understand your point but indeed I am sceptical: in the current setup, not using cdn would mean to save, commit, push and serve files that are already well served by a webserver. I don't see the point in doing a job already done. 
If the application evolved to a actual sound npm module, then yes indicating the dependencies and not using cdn could be a good idea.
