### ISSUE TITLE
error caused by getDarkMode in edit page

### ISSUE THREAD

**Issue by raashika03** [edamontology/edam-browser#154]
https://user-images.githubusercontent.com/45493793/116454832-051c0480-a87e-11eb-8f93-b1be1a508e52.mp4

There's some unexpected behaviour on propose change pages.
@bryan-brancotte Please check, because of which commit this get generated.
Even that theme-button is not showing.

**Comment by raashika03** [comment]
I understood everything thank you!

**Comment by bryan-brancotte** [comment]
Hi @raashika03 

I removed the theme button with 095b1ec8ad54d3c3147459b8972f6d47275773cc : it was missplaced, and "As the theme is chosen in the main UI, we can keep on using the choice of the user."

**Comment by raashika03** [comment]
Yes @bryan-brancotte I understood later on after checking the commits in edit.html file. Thanks a lot again.
