### ISSUE TITLE
Remove repeated links for social media handles!

### ISSUE THREAD

**Issue by secrashi** [edamontology/edam-browser#158]
Links for social media handles are added on the top of the page, as well as in the footer. I think there is no need of mentioning them twice, so we could remove one of them. So, I propose to remove the handles from the footer section. This is a simple task so if @bryan-brancotte @matuskalas  @hmenager can give me a thumbs up for this, I'll make a PR!

**Comment by raashika03** [comment]
Please check [this](https://github.com/edamontology/edam-browser/pull/143#issuecomment-828239348) discussion.

**Comment by secrashi** [comment]
Oh, thanks for letting me know buddy! I'll close this then!
