### ISSUE TITLE
Improve theme button location

### ISSUE THREAD

**Issue by bryan-brancotte** [edamontology/edam-browser#159]
Theme button location is not natural I think, I already expressed it in https://github.com/edamontology/edam-browser/pull/150#issuecomment-828484969 I even removed the button from the edit page with 095b1ec8ad54d3c3147459b8972f6d47275773cc. I think work need to be done to find a proper location. UX/UI skill might me needed.

**Comment by SJellen** [comment]
<img width="721" alt="Screen Shot 2021-04-29 at 11 38 18 AM" src="https://user-images.githubusercontent.com/51421669/116578880-d9316b00-a8df-11eb-8b03-a0cb9be1c76e.png">


Here is my 2 cents
The vertical lines are to show a separation from the main content not necessarily  an actual line

**Comment by sunny775** [comment]
Hi @bryan-brancotte . I'll make a PR for this issue

**Comment by bryan-brancotte** [comment]
And btw thanks to @SJellen for your suggestion !
