### ISSUE TITLE
Loading animation for Edam browser 

### ISSUE THREAD

**Issue by raashika03** [edamontology/edam-browser#161]
[Not so urgent]
how about adding a loading animation here

https://user-images.githubusercontent.com/45493793/116623060-49350500-a963-11eb-8526-4325525547f5.mp4

To inform user that some action is in progress. Tree loading is slow in screens of smaller sizes. 
Like here in this website:
This one I'm showing just as an example, if agreed upon I'll implement it with better design.

https://user-images.githubusercontent.com/45493793/116623592-16d7d780-a964-11eb-8e23-db7126a391d8.mp4

Will this be useful? For users. 
It's always a good practice to let users know what's happening rn.
@bryan-brancotte @matuskalas @hmenager

**Comment by raashika03** [comment]
I noticed that a loading animation is generated only for meta-info at its location only after this [commit](https://github.com/edamontology/edam-browser/commit/f311af3a2052effa18b2d0939444925b3da2319c) which added that as a button. is this generated by default @bryan-brancotte.
I'll dig more on this If not so.

**Comment by bryan-brancotte** [comment]
Hi @raashika03 
I remember at a time there was a loading, but then I removed it, don't remember why. Indeed if loading the json take 7s a loading would be needed.
This issue requires "only" css skills, a good first issue to show css skills.

**Comment by raashika03** [comment]
Ok @bryan-brancotte thank you for the review. I'll take it. :)
