### ISSUE TITLE
Add term detail in a floating panel in full screen

### ISSUE THREAD

**Issue by bryan-brancotte** [edamontology/edam-browser#167]
In https://github.com/edamontology/edam-browser/issues/157 the goal was to make use a unused space in the lower part of the screen. After fullscreen became active, the wasted space became partiaccly resolved and the need of the detail of the term in fullscreen [arrise](https://github.com/edamontology/edam-browser/issues/157#issuecomment-829335940). 

There already is a floating panel, but with very few information :
![tooltip](https://user-images.githubusercontent.com/11556772/116576341-c2a30800-a90f-11eb-85a6-48dfb4193b85.gif)

The idea would be to re-use code generating the right panel, to put the content also in the tooltip and achieve such look:

![draft](https://user-images.githubusercontent.com/11556772/116607521-60a7ca00-a932-11eb-82a3-3ba6dda53804.png)

**Comment by pooja2299** [comment]
Is someone working on it or can I work on it?

**Comment by bryan-brancotte** [comment]
Hi @pooja2299 thanks for you interests, I will take care of it as I have some precise idea of what should be done and don't want to bother someone by saying at every line of code "write that here, write that there, ..."
