### ISSUE TITLE
Edam Logo looks distorted in dark theme!

### ISSUE THREAD

**Issue by secrashi** [edamontology/edam-browser#184]
I noticed that the Edam logo looks distorted when we switch to the dark theme. It is distorted in light theme too but it isn't visible there. 
![WhatsApp Image 2021-05-11 at 10 35 07 AM](https://user-images.githubusercontent.com/56053777/117761516-17fee380-b245-11eb-8a92-c232544711f3.jpeg)

I tried opening the SVG file in Adobe Photoshop, but it won't open up with the layers. So, I can design it from scratch but I need some details like font style and shadow amount, I can design a similar logo without these values too, but with the help of these values I can make the exact same logo. 
Also, I know that many changes to the logo have been proposed, so If we decide to use another logo instead of this, that would work too!

**Comment by bryan-brancotte** [comment]
Hi

It is not distorted, it is just in very poor quality.

The logo is a big discussion as you saw with see https://github.com/edamontology/logoi and https://github.com/edamontology/edamontology/issues/666

The current logo is just the conversion in svg of the jpg/png I found. I/we are waiting for the new logo to be chosen/created/selected/published/... not that the "new" logo could be the same, but prettier. You can if you want submit a logo in logoi repo !
