### ISSUE TITLE
Redirection from old ifb-elixirfr.github.io

### ISSUE THREAD

**Issue by matuskalas** [edamontology/edam-browser#192]
It's super-awesome that the old EDAM Browser links redirect to the new site! 🚀🥇🙌🏽

However, https://ifb-elixirfr.github.io/edam-browser/#http://edamontology.org/data_0842 redirected to https://edamontology.github.io/edam-browser/#topic_0082. Is that expected?

**Comment by matuskalas** [comment]
I see, it just opens my last viewed concept in the EDAM Browser, the same as https://edamontology.github.io/edam-browser. It's, however, super confusing in this case.

(And also, as discussed before, pasting #data_0842 into the URL doesn't help.)

**Comment by secrashi** [comment]
Hi @matuskalas 
> (And also, as discussed before, pasting #data_0842 into the URL doesn't help.)

 I noticed that after pasting #data_0842 into the URL, I have to press enter, then reselect the link and press enter, and then it will be loaded. I attached a video showing the same. I think that to load the URL after altering it, it requires the website to be reloaded two times. I also checked this for other terms. 

https://user-images.githubusercontent.com/56053777/118369996-483adf00-b5c3-11eb-926e-8daf8754288f.mp4

**Comment by bryan-brancotte** [comment]
Hi

It use to be a simple meta refresh, which did not transfer the hash so the browser use the last seen term. 

Indeed copy pasting the hash does not work for the first try, it works on the second try in chrome as you also found @secrashi . It even do not work with firefox. In the later you have to F5 or Ctrl+R. Not very user friendly I agree.

Now I passed to JS forward, along with the hash, you can try it with : https://ifb-elixirfr.github.io/edam-browser/#http://edamontology.org/data_0842 and then https://ifb-elixirfr.github.io/edam-browser/#topic_0084

**Comment by matuskalas** [comment]
Wow, super cool how it works now 🙌🏽🙌🏽
🥇 @bryan-brancotte !
