### ISSUE TITLE
Use logo as favicon

### ISSUE THREAD

**Issue by bryan-brancotte** [edamontology/edam-browser#197]
Following an idea of @secrashi in https://github.com/edamontology/edam-browser/pull/186

As logo will be shipped [into the ontology file](https://github.com/edamontology/edam-browser/pull/186) (owl/json/...) it would be nice to change the favicon accordingly to what is proposed inside the ontology. It should be dynamical, and fallback to the old favicon.ico when no icon is specified in the ontology file.

**Comment by HagerDakroury** [comment]
Shouldn't this be closed following 7096433 ? @bryan-brancotte

**Comment by bryan-brancotte** [comment]
Hi @HagerDakroury almost as I forgot to do it for the favicon, PR incomming.
