### ISSUE TITLE
Scrolling to selected concepts / scroll-into-view

### ISSUE THREAD

**Issue by hmenager** [edamontology/edam-browser#207]
## Specification

When searching for a given concept in EDAM, the scrolling seems to often fail to reposition the view to properly show it in the tree.

### Devices

Laptop and Desktop

### Browser

Firefox 88.0.1 (64 bits)

## Message

Reproduce:
- open https://edamontology.github.io/edam-browser/
- search for e.g. FASTA, and select the first proposed concept in the autocomplete list --> scrolling happens but does not reach the position of FASTA
- same for Genomics

See here:

![edam_search_terms_scroll_bug](https://user-images.githubusercontent.com/1140736/120164019-68d97a80-c1fa-11eb-985b-65ecd4d20098.gif)

**Comment by HagerDakroury** [comment]
Can reproduce yes.

How should duplicates be handled in such case? scroll to the first one ?

**Comment by bryan-brancotte** [comment]
Hi

I don't know if we ever had the "scrool into view", but would be a cool feature.

**Comment by hmenager** [comment]
We had it I think, I really liked it a lot.
And, yes, @HagerDakroury , scrolling to the first one by default is the best option.

**Comment by bryan-brancotte** [comment]
After some trying, I think we can have the feeling of the scrool-into-view with topics as they most of the time open in front of us. With Data it clearly is not the case. I think I added the bold path to the selected elements in order to help finding selected element, and thus because there is no scroll into view. When looking at the code, specifically where we expand all node to the selected node with [`browseToFromElement`](https://github.com/edamontology/edam-browser/blob/e87278b6771f8521f0c845d21ff1099551d99abb/js/tree-reusable-d3.js#L477-L506), we do not see any mention of moving the tree so selection go into the view.

Setting it as a new feature

**Comment by hmenager** [comment]
you are absolutely right @bryan-brancotte, I just had a look at the behaviour of EDAM browser in releases v1.0.0 and v1.0.1, and this didn't work either :disappointed: 
I think this would be a very nice feature to implement though, very useful for the user experience.

**Comment by bryan-brancotte** [comment]
Hi, @HagerDakroury here are some idea/suggestion for this issue.

When the user click on a node, [here](https://github.com/edamontology/edam-browser/blob/main/js/tree-reusable-d3.js#L366-L368) we call the `clickedElementHandler` to indicate that indeed it has been clicked, then this handler ask to set the element  [selected](https://github.com/edamontology/edam-browser/blob/main/js/tree-edam-stand-alone.js#L621-L628) which is done [there](https://github.com/edamontology/edam-browser/blob/be854d39b5b1a8a53f9a8293c888d62a1c0d56fb/js/tree-reusable-d3.js#L636-L647). This selection expand the tree where it is needed. We can either after that scroll into view, or make it possible in an other function. I would rather go for the second option as it allows to disable the scroll into view, but allows to do multiple (un)selection of elements, and only after scroll into view.

I think we should add a new method [here](https://github.com/edamontology/edam-browser/blob/be854d39b5b1a8a53f9a8293c888d62a1c0d56fb/js/tree-reusable-d3.js#L648) which would be something like 
```
    /**
     *
     * @param {string[]} identifiers - the identifiers that should be visible after the call of this method
     */
    cmd.moveIntoView = function (identifiers) {
        console.log("Asked to put into view node " + identifiers[0]);
    };
```
We should already be prepared for a list of identifiers as anyway an identifier-> multiple nodes, so the code will be ready if the bookmark of multiple term is implemented. If you think it complicate the implementation to much, we can go for `unction (identifier) {`

**Comment by HagerDakroury** [comment]
> I would rather go for the second option as it allows to disable the scroll into view, but allows to do multiple (un)selection of elements, and only after scroll into view.
> 
I agree it should be as reusable and encapsulated as much

>      * @param {string[]} identifiers - the identifiers that should be visible after the call of this method
>      */
>     cmd.moveIntoView = function (identifiers) {
>         console.log("Asked to put into view node " + identifiers[0]);
>     };
> ```
> 
> We should already be prepared for a list of identifiers as anyway an identifier-> multiple nodes, so the code will be ready if the bookmark of multiple term is implemented. If you think it complicate the implementation to much, we can go for `unction (identifier) {`
> 
> Hoping this will help
> 
I have a question, do identifiers here refer to the selected element and its possible duplicate (same term in other branches)? + would any other elements other than identifier[0] be accessed inside the function?

**Comment by bryan-brancotte** [comment]
the identifier is the one identifying the element and all it duplicate. The catch is that we do not have a dict translating the identifier, we would have to find it each time... cpu consuming. Instead we could have 
```
    /**
     *
     * @param {Object[]} elements - the identifiers that should be visible after the call of this method
     */
    cmd.moveElementsIntoView = function (elements) {
        console.log("Asked to put into view node " + elements[0]);
    };
```
and do after this [line](https://github.com/edamontology/edam-browser/blob/main/js/tree-edam-stand-alone.js#L626) a 
```
            __my_interactive_tree.cmd.moveElementsIntoView([d]);
```



We/You could event start with a `moveElementIntoView(d)` with only one element, it would break the new feature in simpler subtasks to tackle

**Comment by HagerDakroury** [comment]
> the identifier is the one identifying the element and all it duplicate. The catch is that we do not have a dict translating the identifier, we would have to find it each time... cpu consuming. Instead we could have
> 

ohh, got it!

> We/You could event start with a `moveElementIntoView(d)` with only one element, it would break the new feature in simpler subtasks to tackle

Yes makes sense. I'll start with this

**Comment by HagerDakroury** [comment]
> 
> and do after this [line](https://github.com/edamontology/edam-browser/blob/main/js/tree-edam-stand-alone.js#L626) a
> 
> ```
>             __my_interactive_tree.cmd.moveElementsIntoView([d]);
> ```

so a bit of an update @bryan-brancotte. I figured it out with zoom handler and the scaling aspects but as it turns out this [line](https://github.com/edamontology/edam-browser/blob/main/js/tree-edam-stand-alone.js#L626) is not triggered when you click an element on the search bar (a bit of a late discovery) it's only applicable when clicking on the node.

I'm currently trying to trace the code and figure out where exactly can we catch the clicked-on-a-searched-item event and get the element's data from there.

**Comment by HagerDakroury** [comment]
> which is done [there](https://github.com/edamontology/edam-browser/blob/be854d39b5b1a8a53f9a8293c888d62a1c0d56fb/js/tree-reusable-d3.js#L636-L647). 

So, looks like the best place to call the function is in here (triggered in all selection events). Do you think this is the correct direction? @bryan-brancotte

**Comment by HagerDakroury** [comment]
Hi @bryan-brancotte, I'm trying to implement centring the node when loading the window for the first time, but looks like we can't access the specific node from there (from the start). And indication where to trace it?

**Comment by bryan-brancotte** [comment]
> ... can't access the specific node from there ....

There might be a link missing associated with "there" ?

(working on your question)

**Comment by HagerDakroury** [comment]
> There might be a link missing associated with "there" ?

yeah my bad 😄, I meant from the [startup](https://github.com/edamontology/edam-browser/blob/97de559807f794d7a52526f5166b735afbc0fc0b/js/index.js#L65). I tried tracing the calls and the best I can get is the URI, trying to get the node object (which contains x0,y0) from it.

**Comment by bryan-brancotte** [comment]
> ... The catch is that we do not have a dict translating the identifier, we would have to find it each time... cpu consuming. 

I was wrong : https://github.com/edamontology/edam-browser/blob/3be2455ef92b42924a06afcd86e9152858e1034e/js/autocomplete-edam-reusable.js#L71-L73

So when using it in loadingDoneHandler : 

```diff
diff --git a/js/tree-edam-stand-alone.js b/js/tree-edam-stand-alone.js
index e2662c7..75ff22e 100644
--- a/js/tree-edam-stand-alone.js
+++ b/js/tree-edam-stand-alone.js
@@ -684,6 +684,11 @@ function interactive_edam_browser(){
         .loadingDoneHandler(function(){
             __my_interactive_tree.cmd.selectElement("http://edamontology.org/"+getInitURI(current_branch),true,true);
             __my_interactive_tree.cmd.selectElement(getInitURI(current_branch),true,true);
+            setTimeout(function(){
+                __my_interactive_tree.cmd.moveElementsIntoView([
+                    __my_interactive_tree.cmd.getElementByIdentifier(getInitURI(current_branch))
+                ]);
+            }, 10);
             build_autocomplete_from_edam_browser(browser);
             $(".loader-wrapper").fadeOut();
         })
```

I has to wrap it in a setTimeout to give time to the rendering to be somehow done, but I don't like it, If you find a way to improve :pray: , do not hesitate !

**Comment by HagerDakroury** [comment]
I don't think a timeout is such a problem here (unless we can find a point in the code where we're absolutely sure the tree is loaded) I tried `reset` for that but seems like not all node data is loaded.

So, I guess that's good to go for now!

**Comment by bryan-brancotte** [comment]
Hi @HagerDakroury 

To add to functionnality desribed by @hmenager in https://github.com/edamontology/edam-browser/pull/214#issuecomment-860536311, I think the move into view could also be triggered when clicking on an [interactive_edam_uri](https://github.com/edamontology/edam-browser/blob/97de559807f794d7a52526f5166b735afbc0fc0b/js/tree-edam-stand-alone.js#L412)

**Comment by HagerDakroury** [comment]
> interactive_edam_uri

Wouldn't that trigger the centering on-click even if it's disabled? (debugging confirmed). I think to enable that, we'd need to place it elsewhere. Can we exclude node clicks inside [interactive_edam_uri](https://github.com/edamontology/edam-browser/blob/97de559807f794d7a52526f5166b735afbc0fc0b/js/tree-edam-stand-alone.js#L412) ?

**Comment by bryan-brancotte** [comment]
Indeed it would !

Maybe instead of
```
            if($("input[name='center-node-click']:checked").length)
                __my_interactive_tree.cmd.moveElementsIntoView([d]);
```

we should expose a method
```
    /**
     * Read-only proxy to use the textAccessor of the interactive_tree
     * @param {Object[]} elements 
     * @return {object} the value return by the textAccessor for the given parameter
     */
    browser.moveElementsIntoViewWhenEnabled = function(elements) {
            if($("input[name='center-node-click']:checked").length)
                __my_interactive_tree.cmd.moveElementsIntoView(elements);
    };
```

and use it in the loadingDoneHandler, the interactive_edam_uri, and the clickedElementHandler ?
