### ISSUE TITLE
Add a button next to the url identifier to easily copy the actual edam url

### ISSUE THREAD

**Issue by bryan-brancotte** [edamontology/edam-browser#40]
For now we can only copy the link to browse the EDAM element within the browser, not juste the link

From a need raised by @jvanheld and an idea of @thomasrosnet, add a button something like the copy link when cloning a repo in github
![Capture d’écran de 2020-09-25 12-59-57](https://user-images.githubusercontent.com/11556772/94259716-340c7980-ff2f-11ea-9183-4bace42b050f.png)

**Comment by bryan-brancotte** [comment]
Following a discution in #43 some user might be confused by a link that suggest it goes to  http://edamontology.org/format_3620 but in the end points to https://ifb-elixirfr.github.io/edam-browser/#format_3620

Maybe consider not having a link at all ? Only look like one ?

**Comment by matuskalas** [comment]
A good point that this might be confusing 🤔

I'd suggest thinking and discussing what would be the best...
(personally no good idea now on Friday eve🤯)

**Comment by bryan-brancotte** [comment]
I agree with you, Friday eve is not the best time to think about it

**Comment by matuskalas** [comment]
Ok, just two tries (perhaps to be found a bad Friday-eve idea later, but anyway 😊):
 - Would it make sense with the URI being itself not clickable, but having 2 (or more) buttons next to it, incl. "Open here" & "Open in BioPortal"?
 - URI not clickable, no buttons (except maybe the copy button, but then with the URI itself (would it then also be useful for the short ID?)). There are links to other browsers on the bottom right, so perhaps no need to duplicate.

**Comment by bryan-brancotte** [comment]
I would vote for option 2, with a button like in the description of the issue, allowing to copy the uri, this button could then appear after each link related to an uri. Hereafter an example of where the uri-copy-button could be added, in red

![Capture d’écran de 2021-03-12 17-02-51](https://user-images.githubusercontent.com/11556772/110965929-02f4f980-8355-11eb-8ad9-d9af69d71d73.png)

**Comment by matuskalas** [comment]
Sounds good to me.

Perhaps the other concepts there don't need it though?

But I'd suggest considering adding a short ID line, which could then have the button too. _E.g._ `operation_2520`

The copying of both the long URI and the short ID would be useful when doing some annotation / editing some data.

**Comment by Babsbarokah** [comment]
Hi, 

The primary issue(problem) is to copy the correct URL link easily.

Possible solution raised is (i) to create a (copy link) button (ii) have a more button next to the URL(which is not clickable) (iii) have a copy button ( of the long URL) with a short ID (iv) have a copy button appears after each link

The end goal is to copy the correct link while making the process smooth and easy,(which may involve discovering, adding/removing features)

Process.
As identified that both the long URL and short ID are useful in the long run, it would be good to incorporate both without complicating and altering the interface of the browser. Also mentioned is the fact that other links are present at the bottom right of the browser. All these issues and functions(raised and unraised; which might be discovered while working on it) need to be addressed accordingly as a whole for consistency and to make the UX smooth from start to finish.

Can I work on this, please?

**Comment by matuskalas** [comment]
Thank you @Babsbarokah for your interest, please go ahead & all the best! 👍🏽

@bryan-brancotte @hmenager is there any clarification or conclusive suggestions we should provide? Can of course also be after we see first @Babsbarokah pull request...

**Comment by Babsbarokah** [comment]
Great, thanks.

I'd get to it and keep the team informed.

**Comment by Babsbarokah** [comment]
Here is an update on the Copy-able URL button

Link-  
https://www.figma.com/proto/dTgV6HFPybn767Q7Mnm6sz/EDAM-ontology?node-id=8%3A4&scaling=contain&page-id=0%3A1 or 
https://www.figma.com/file/dTgV6HFPybn767Q7Mnm6sz/EDAM-ontology?node-id=0%3A1

Kindly let me know your feedback on this as I proceed to the wireframing and prototyping stage, thanks.

#82 was also addressed.

**Comment by bryan-brancotte** [comment]
Hi @Babsbarokah 

You indeed correctly formalize the issue, I just hope you did not used to much time in doing such presentation. Your sketch look like what was suggested before, I thus understand that you agree with the design, so I recommend you to go ahead, develop and start a PR.

As you point out, #82 would be solved by completing this issue.

**Comment by bryan-brancotte** [comment]
_#82 contains the start of a discussion of readability of the URI. Solution for this issue should thus address both usability and readability of the URI_

**Comment by Babsbarokah** [comment]
The prototyped link I provided is in line with the design phase for clear, proper documentation and future reference/modifications.

I used available suggestions to build on the solution with some improvements.

I'd go ahead with this and reach out with progress and perhaps need help.

Thank you.

**Comment by Babsbarokah** [comment]
Hi @matuskalas @bryan-brancotte 

I have finished redesigning this issue, here is the updated link https://www.figma.com/file/dTgV6HFPybn767Q7Mnm6sz/EDAM-ontology?node-id=0%3A1
What particular file am I changing/adding to send a PR

**Comment by bryan-brancotte** [comment]
Hi @Babsbarokah 

I missed your message of April 25th sorry. The design looks good, to be honest I don't see the difference with what it was at the moment of https://github.com/edamontology/edam-browser/issues/40#issuecomment-815377028 . For future work in issue, and not limited to this project, I recommend you that you keep information inside the issue and not third party service. For example here it is hard for me to know what changed you made. Also writing presentation look good, but consume way more time than just writing inside an issue, along with screenshot/photos.

So regarding this issue, and if you want to continue working on it (you can decline it don't worry), the next task is to `git clone` the repo, and start understanding what files do what and thus find where to change the code to implement your design proposal.

**Comment by Babsbarokah** [comment]
Hi @bryan-brancotte thank you for your honest feedback. I'd work on this. The design I made was to a part of the website; in reference to the copy button and ID raised. Please see attached image of the original website and the replication I did below.

The next task to git clone, I'd give it a shot and let you know my progress on it, thanks.
![Screenshot_20210506-062703~2](https://user-images.githubusercontent.com/81495038/117246565-c87b7a80-ae34-11eb-815f-139237018066.png)

**Comment by bryan-brancotte** [comment]
Hi,

I would like to highlight that this issue is about adding a button next to URI in order to copy them easily. It is not about improving the theme and/or removing rounded border. In a PR it is recommended to solve one issue at a time (https://github.com/edamontology/edam-browser/blob/main/CONTRIBUTING.md).

In the browser we use bootstrap, and this lib has a very convenient way of adding a button right after an input. I think it should be used (spare time when developing, easier for others to understand)

**Comment by bryan-brancotte** [comment]
Hi @HagerDakroury 

I searched for copy-link, the github one is convenient (I fell). I also look at the stackoverflow one but it does not fit our needs. Here after are suggestion of presentation.

![Capture d’écran de 2021-06-04 11-18-16](https://user-images.githubusercontent.com/11556772/120779318-3d6ecc80-c527-11eb-98f9-8f81665f7d18.png)

I also think that we should be able to copy the URI also for parent, has_topic, has_output, has_xxx. You will probably have to change interactive_edam_uri itself rather than appending the copy-button after.

Here are th html sketch of the suggestion:

```html
<div class="input-group input-group-sm">
    <input type="text" tabindex="1" class="form-control bg-edam-operation-light fg-edam-operation border-one-solid border-edam-operation" onclick="$(this).select();" autocomplete="off" data-autoselect="" readonly="" value="http://edamontology.org/operation_2520" style="font-size: initial;">
    <span class="input-group-btn">
        <button class="btn bg-edam-operation fg-edam-operation-light" type="button"><i class="fas fa-copy" style="
"></i> URI</button>
    </span>
</div>
```
```html
<div class="btn-group btn-group-xs">
  <button type="button" class="btn btn-sm bg-edam-operation-light fg-edam-operation border-one-solid border-edam-operation" style="font-size: 1em;">
    Operation_2520
  </button>
  <button class="btn bg-edam-operation fg-edam-operation-light" type="button" style="font-size: 1em;">
    <i class="fas fa-copy"></i>  URI
  </button>
</div>
```
```html
<div class="btn-group btn-group-xs">
  <a href="#http://edamontology.org/topic_0196" 
     role="button"
     onclick="browser.interactive_tree().cmd().clearSelectedElements(false);browser.interactive_tree().cmd().selectElement('http://edamontology.org/topic_0196',true)" 
     class="btn btn-sm bg-edam-topic-light fg-edam-topic border-one-solid border-edam-topic" 
     style="font-size: 1em;"
     >Sequence assembly
  </a>
  <button class="btn bg-edam-topic fg-edam-topic-light" type="button" style="font-size: 1em;">
    <i class="fas fa-copy""></i> URI
  </button>
</div>
```

I have a preference for the link+button to copy choice, the last html snippet. What are your views @HagerDakroury ?

**Comment by HagerDakroury** [comment]
@bryan-brancotte , those look good! and you're right, if it's intended to be reusable across all terms, then it makes sense to have it as part of the row not concatenated.

I have a concern though regarding the UI. Don't you think the icon+URI is a bit verbose? (especially when the details panel appears as a tooltip) . I always see it used only as an icon optionally with a tooltip indicating the function.

What do you think?

**Comment by bryan-brancotte** [comment]
I agree with you, icon+URI is crowded but on the other hand has we would be copying the URI not the text it could be confusion to clic on copy `Sequence Assembly` and get an URI. Maybe only the icon and a little toolitp like you did indicating after the clic that the URI have been copied ?

**Comment by HagerDakroury** [comment]
Should the button be added to only the URI or ALL concepts (topic, parent, etc..)? cc @bryan-brancotte @matuskalas

**Comment by bryan-brancotte** [comment]
Hi, Yes definitly, this button should help to copy the URI of all term displayed on the right.
