### ISSUE TITLE
Add double parent for entity from the browser

### ISSUE THREAD

**Issue by aizquier** [edamontology/edam-browser#41]
Following the question asked on issue [#38](https://github.com/edamontology/edam-browser/issues/38), where we asked for the possibility of defining multiple parents for an entity in the JSON ontology file, now we are interested to know if it is possible to do it  directly in the edam browser. Our interest is to allow users not familiar with JSON to perform such operation. Thanks!

**Comment by bryan-brancotte** [comment]
Hi @aizquier 

When clicking on the pencil or plus symboles on the top right, you access to a form which allows to define multiple parent. The edition of the json is not straitforward, the edition workflow for editing the ontology in edam browser goes through a github issue and manual edition by edam curator. Nevertheless you could add a new action to this edit form which would be to download the json with the edition proposed by the user.

**Comment by raashika03** [comment]
Is this issue still needed to be work upon.

option to download the data (which goes for now on github as PR after edition on edit page) in json format. Is all needed to be done in this issue right? @bryan-brancotte

**Comment by bryan-brancotte** [comment]
Downloading part of the ontology is not in the scope for now, closing
