### ISSUE TITLE
Filter searchable concepts when suggesting new / updating existing concepts

### ISSUE THREAD

**Issue by hmenager** [edamontology/edam-browser#48]
The current interface allows to select terms from the ontology to specify the relationships in a new concept / updated concept proposal.
However, the interface does not filter on concept type (e.g. it is possible to specify a format in the has_topic relationship).
This interface should filter:
- [ ] `same type` for the `Parent`
- [ ] `topic` for `has topic`
- [ ] `data` for `is format of`
- [ ] `data` for `has input`
- [ ] `data` for `has output`

**Comment by HagerDakroury** [comment]
Hi @hmenager, I'd love to start working on this! I think I stumbled upon where to start when I was exploring the code for another issue. I spent some time around it so I might as well continue :smiley:

**Comment by hmenager** [comment]
Just assigned this to you @HagerDakroury. Feel free to give it a try!
