### ISSUE TITLE
Accept ES6 code

### ISSUE THREAD

**Issue by bryan-brancotte** [edamontology/edam-browser#57]
Considering that ES6 is well supported ([97.53%](https://caniuse.com/?search=ES6)), test should be adapted to accept code using ES6 notation such as in https://github.com/edamontology/edam-browser/pull/56/commits/287b4cdefb610ae48f62d4e3a70bfbb27283c196 :

Hints:
 * look at the commit of @HagerDakroury and understand why the test have failed while the code was sound
 * look at the execution of the test by itself, and adapt it so it would have accepted this commit
   * not familiar with GitHub ? Look at the red time before "fixed duplicate parents bug"
 * create a pull request with you changes

**Comment by Marlene7963** [comment]
Please assign me this task @bryan-brancotte please assign me this task
