### ISSUE TITLE
Dark theme for edam-browser

### ISSUE THREAD

**Issue by raashika03** [edamontology/edam-browser#60]
This will look like this or better than this:
This's an image using dark reader, a third party application.
![Screenshot from 2021-03-31 00-03-45](https://user-images.githubusercontent.com/45493793/113038969-c3cc0280-91b4-11eb-944c-c7c183eb746a.png)
May be some option to change the theme can be provided on the main page like on github, to transition between light and dark mode
![Screenshot from 2021-03-31 00-00-22](https://user-images.githubusercontent.com/45493793/113039229-11486f80-91b5-11eb-8c11-98d04035444c.png)
Since, an issue has been raised regarding the colour contrast for easiness for some people, so this might be a good feature to implement, I think.

**Comment by HagerDakroury** [comment]
Looks super cool! 
With a better font for the tree map(it looks a bit unreadable in the picture), would be a decent feature!

**Comment by hmenager** [comment]
Excellent @raashika03, @HagerDakroury, this would indeed be an excellent feature to add. And indeed, the current font for the tree does not fit with the dark theme.

**Comment by hmenager** [comment]
@raashika03 I assigned this to you as you suggested it first, but feel free to refuse if you'd rather focus on something else :smile:

**Comment by raashika03** [comment]
ok sure @hmenager I'll check what can be done.

**Comment by hmenager** [comment]
I also added @HagerDakroury if she'd like to collaborate with you (just discovered tonight you can have multiple assignees for an issue).

**Comment by Marlene7963** [comment]
Can I help work on this too?

**Comment by raashika03** [comment]
> Can I help work on this too?

Hi @Marlene7963 most welcome :) I'm glad that you're willing to help on this. But I'm working on this so there are high chances of conflict generation if both of us will work together, cause I might be planning of some other ways to implement this theme while you'll think of some other thing. So, it's not possible to work simultaneously by commit submission. But I'm open to your suggestions of any ideas as like Hager gave above. You're free to review and comment when I'll update my commits. And then later on, you can also add up any commits if required but till that time let me do at least a base kind of thing for this issue which I've in my mind.

**Comment by raashika03** [comment]
![Screenshot from 2021-04-01 11-21-47](https://user-images.githubusercontent.com/45493793/113249583-8d89a280-92dc-11eb-91e3-3d0a5d8ed200.png)
@hmenager @matuskalas @bryan-brancotte Please have a look if this theme (overall) is fine, many changes are still left but I want to know if the main theme is ok so that I won't have to change everything again, I followed the theme idea of ubuntu 20.04 mainly. I thought this theme is more appealing and comfortable to the eyes. Most of the text editors like sublime is also having this theme as default.

**Comment by raashika03** [comment]
Hi @hmenager @bryan-brancotte @matuskalas! this's the link showing the complete dark theme for all the pages of the edam-browser. Please check it out.
[video](https://youtu.be/ZHPQjfeG1ao)
Since, file size is large so sharing it via youtube :p

There were things which I couldn't change, which are controlled in default by browsers (chrome, mozilla...) I checked for their code but I couldn't find them, so thought to leave them as it is.
Example:
1) when we load custom, and type the url, then the suggestion box which appears, I think thats controlled by chrome (I've the login there) cause it has the history and I wasn't able to change it's colour cause couldn't find its code anywhere in the repo. 
2) "Please fill in this field" is also same case I think. I didn't find its code in the repo.
3) Scrollbars same case (May be this can be changed by separate definition of scrollbar with styling). Right now its default by chrome.
For these three I wasn't able to get the code by "Inspect- ctrl+shift+I" even on the chrome-developer tool. So, ig these are by default by chrome.
Proof:
Comparison chrome vs mozilla:

Important:
I couldn't store the theme chosen by the user. so whenever user refreshes or reloads the page, default theme is loaded. Wasn't able to store like "in github dark theme mode" because edam browser doesn't stores user input/ information. Remember no login/sign in/ sign up required :p
So each time they need to use theme button :(
Same cases with the propose change pages.
Very Important:- But this can be extended to store in future by providing the option to sign up/ sign in.
So, then it'll be like github then.
  
Reasoning for why I did like that:
1)Placed the theme button above the details table, cause other positions were not looking nice, it should be placed only at the top cause user will find it convenient there to use. Didn't placed it in the header because that was looking like a separate entity there, screwing the look.

Which one looks better, I'm confuse.
![Screenshot from 2021-04-02 08-43-55](https://user-images.githubusercontent.com/45493793/113376971-ac497100-9390-11eb-8187-6d7ff7524101.png)
![Screenshot from 2021-04-02 08-13-12](https://user-images.githubusercontent.com/45493793/113376973-ae133480-9390-11eb-8fe7-dbb3e04d2865.png)

Share your opinion so that I can create a PR asap :)

One question, I don't understand why this was labeled as a good first issue :( there was so much work in this, cause I changed styling for every element manually (felt like styled the whole edam-browser :p). Didn't use any dark theme tool by third party, cause those themes, didn't cover every element specifically. so many elements had the same colour (overriding was possible but that won't be nice for future maintainers ig). So those were not so appealing. I tried few of them before.

**Comment by bryan-brancotte** [comment]
Hi @raashika03 

Great work ! Hereafter some remarks:

 * Indeed some elements are browser dependent and customizing it is a "little" tricky and we can leave it as is instead.
 * the edam-browser does store information, I let you find where (you'll have to dive into the js code).
 * This issue was label good first as it is "only" css, but indeed theme-ing can be long.
 * In android we can set the os to dark, so browser receive this information and website knows it too. Extension can also be added to chrome to automatically enable dark mode. All of this to say that there is a way in css to select between light/dark theme based on the browser settings.

Do not hesitate to make a PR even when work is not completed, it allows us to see the code you produce.

**Comment by raashika03** [comment]
>
> * the edam-browser does store information, I let you find where (you'll have to dive into the js code).
Does this mean only 1 button at the main page will be needed to change the theme and on refresh also that theme state will not change itself cause edm stores the state of an object? Did I understand things correctly @bryan-brancotte  
>
> * In android we can set the os to dark
Not for all the versions
Dark theme is available in Android 10 (API level 29) and higher.
We can't set the theme to dark (I'm taking about complete dark theme not partial which is available in general on chrome and mozilla) for lower version in os ,only we can force by [this](https://www.geeksforgeeks.org/how-to-force-dark-mode-on-web-contents-in-chrome/) for chrome don't know about other browsers.
>
>so browser receive this information and website knows it too. Extension can also be added to chrome to automatically enable dark mode. All of this to say that there is a way in css to select between light/dark theme based on the browser settings.
I tried and the result was that image which I uploaded at first while suggesting this issue.
and in that texts were blurred type. and other elements were also not in accordance as we want, so for that I need to override styling for many elements.
And we can't change the theme to some other colour like neon-blue theme if we want to change the complete dark theme. But since I styled manually, so just by changing the colour code for dark-theme class whole theme can be changed at once (little work in css only no change in html code).  
This's the only reason why I didn't use any dark theme from any website.
I tried to follow github which has its separate dark theme. So I wished to create separate theme for edam too (no third party website dependency). 
What if those website will change their dark theme colour in future and we'll not like them, then we won't be having options to change them.

**Comment by HagerDakroury** [comment]
Hi @raashika03 , first of all amazing job! I saw the video and the new theme looks perfect! 😮 

I'll jump in real quick here since I'm a co-assignee in this issue 😄 

> > * the edam-browser does store information, I let you find where (you'll have to dive into the js code).
> 
> Does this mean only 1 button at the main page will be needed to change the theme and on refresh also that theme state will not change itself cause edm stores the state of an object? Did I understand things correctly @bryan-brancotte
> On refreshing or changing the web pages(main page to propose change page) how can we store the input given by the user (dark theme button enabled or disabled) unless that user has some profile maintained on that website (by sign in/sign up).
> 

There are cookies that are set once the main window is loaded, that's why whenever you refresh you get the same branch/term you were viewing the last time and NOT the main page. (here's for example what I land on now when I open the browser)
![1](https://user-images.githubusercontent.com/37930475/113434759-d5462200-93e1-11eb-8c12-b48163596547.PNG)
![2](https://user-images.githubusercontent.com/37930475/113434765-d8d9a900-93e1-11eb-9ccc-d1c574a77969.PNG)

I think you can set the theme as a cookie also, this way it'll be saved until changed.

Hope this helps!

**Comment by raashika03** [comment]
I understood well thank you Hager <3 I'll check for its implementation :)

**Comment by bryan-brancotte** [comment]
Thanks @HagerDakroury for your answer.

@raashika03 i know that not all android have it :disappointed: it is so usefull ! For the preference, I was talking of https://developer.mozilla.org/fr/docs/Web/CSS/@media/prefers-color-scheme anyway, it is a good thing to allow the user to change the theme, I hope both can be combined

**Comment by raashika03** [comment]
> 
>For the preference, I was talking of https://developer.mozilla.org/fr/docs/Web/CSS/@media/prefers-color-scheme 
Thanks for sharing, I wasn't aware of this :)

**Comment by raashika03** [comment]
Closing work done in #96
