### ISSUE TITLE
Creating a more User Friendly Interface

### ISSUE THREAD

**Issue by Gladyzz** [edamontology/edam-browser#63]
I went through the Edam ontology browser and discovered that a lot can be worked on in regards to it's User Interface and User experience.

**Comment by Gladyzz** [comment]
First of all, as a user I didn't quite understand the actions in which the drop down contents on clicking "EDAM" were meant to perform. Being a first time user, I was confused and it took me a while to figure out that it's main aim was to aid the filtering of the data displayed. 

This being said, I believe the filtering process of data can be improved for users in order to save time and improve their experience on the browser.


![Screenshot_20210331-012258](https://user-images.githubusercontent.com/66223616/113073569-3f33b100-91c1-11eb-862b-d96e907f9069.png)

**Comment by Gladyzz** [comment]
Another issue I observed was the "+" button. I thought its main aim was to zoom and make the data displayed broader but I was wrong and discovered that it was to expand and display all branches of the tree. 

A pop-up notification was displayed. However, I believe a better use of icon and pop up instruction can be implemented.

When I wanted to return to how the tree was displayed initially, I clicked on the "Reset zoom" button but realized that it performed an entirely different task. I guess my main reason for doing that was because it was the closest button to the "+" button and in UI/UX related elements are usually grouped together. 

Therefore, I would suggest that the "Collapse not selected elements" button, should be rephrased to " Collapse unselected branches" and it's position should be switched and placed beside the "+" button which can also be adjusted for better User Experience. 

![Screenshot_20210331-020154](https://user-images.githubusercontent.com/66223616/113076199-72c50a00-91c6-11eb-920b-4ca404f6f4e5.png)

**Comment by Gladyzz** [comment]
Please I would be grateful if I am assigned to this task 🙏🏾

**Comment by bryan-brancotte** [comment]
Hi @Gladyzz, I agree with your arguments, go ahead, I've just assigned this issue to you

**Comment by Gladyzz** [comment]
@bryan-brancotte thanks 😇🙏🏾

**Comment by bryan-brancotte** [comment]
You are welcome :)

Just a quick precision, I wanted to "hide" the "expand all tree" button as expending can consume cpu ressources, but clearly in term of UX design it was a bad choice, and there is room for improvement.

**Comment by Gladyzz** [comment]
@bryan-brancotte lol now I understand why it was like that. But I believe the improvement would actually go a great way in impacting the user experience. Since they come first. 

Thanks for giving me the opportunity to make this improvement 😇.

**Comment by bryan-brancotte** [comment]
Issues raised here were tackled in various issues. Thanks for raising them !
