### ISSUE TITLE
Pop-up button for tree-map box

### ISSUE THREAD

**Issue by raashika03** [edamontology/edam-browser#72]
for screen smaller than a particular size for this [problem](https://github.com/edamontology/edam-browser/issues/69#issuecomment-811913188) discussed there.

I'm working on this. Just created another issue (for easeness for discussion in future) from #69 cause that concluded some separate enhancement feature.

**Comment by raashika03** [comment]
(https://github.com/edamontology/edam-browser/issues/69#issuecomment-811921387) Problem in PS of this comment
>
>P.S: I agree that if we zoom so the whole viewed area is the tree then we cannot escape it, the buttons would not solve the issue completely as if they are not visible at this moment we are still trapped.
Two solution:

1)What if we use some sticky element as the button to skip the tree map box (or to resize it), when tree covers the whole view area. This sticky element will appear only if the tree map box covers the whole view area.
2) Create a sticky vertical scrollbar for the whole page only for smaller screen sizes. This can be designed to appear like in above scenario or for all the conditions for smartphones. At present scrollbar isn't defined, it's by default of very small width leading to the problem. 

2nd sounds better to me @bryan-brancotte it'll solve scrollability issue too for smart phones. Button might look bad (a button appearing on the screen all of a sudden, when whole screen has some other kind of content), while scrollbar goes well with the design and users are habituated with using it. your views?

**Comment by bryan-brancotte** [comment]
Having a way in js to reset window zoom and scroll would help escaping zoom trap. It could be triggered by a click on a button that would float at the bottom right of the screen (something like a back to top link).

This issue is not an easy task, but can be taclked by someone that want to show js and UI skill.

**Comment by raashika03** [comment]
Oki @bryan-brancotte I'll implement it like you suggested.

**Comment by raashika03** [comment]
Hi @bryan-brancotte I think this problem is solved now because of viewport addition. 
There's not as such scrollablility issue now. 
So, I'm closing it. Feel free to add up if I missed anything.

**Comment by raashika03** [comment]
Moreover after addition of button to view tree map on full screen, no one will generally try to enlarge the tree box.
So this pop up button will unnecessarily add up in the content.
