### ISSUE TITLE
Adding clickable Edam logo

### ISSUE THREAD

**Issue by raashika03** [edamontology/edam-browser#75]
How about adding clickable Edam logo 
![7922809](https://user-images.githubusercontent.com/45493793/113466619-dbc4b000-945a-11eb-9667-90386c416500.png)
 
Something like this:
This format looks better to me than the present format.
![Screenshot_2021-04-03-09-38-40-36](https://user-images.githubusercontent.com/45493793/113467442-a4f19880-9460-11eb-8852-d5ceffbef43d.png)

![IMG_20210403_085632](https://user-images.githubusercontent.com/45493793/113466806-28f55180-945c-11eb-9ee6-53cf3b2ac237.jpg)

In the header at the place of Edam and shifting Edam ontology rightward in accordance, that logo will link to [edamontology] (www.edamontology.org) so link in the red box beside Edam explanation can be removed.

Just for beautification purpose I can say :-P

All the websites have their logos displayed at the front page at least so I proposed this. And I couldn't find Edam logo on the Edam browser

**Comment by kellydoleo** [comment]
Hi @raashika03, can I help out with this issue?

**Comment by raashika03** [comment]
Mentor has not yet approved this issue. If needed I'll ask you for your help. Thank you Kelly.

**Comment by bryan-brancotte** [comment]
Hi @raashika03 

I like this presentation for the links to twitter, gitter, and more, could you PR this ?

For the logo, we should for now use https://github.com/edamontology/edamontology/raw/main/EDAMrelations.png (which resolve in 404 as no logo has been selected yet). I don't know if we should show that the image is missing, or [hide it when missing](https://www.geeksforgeeks.org/how-to-hide-image-not-found-icon-when-source-image-is-not-found/)

**Comment by raashika03** [comment]
Oki @bryan-brancotte I'll do so.

**Comment by raashika03** [comment]
> 
>(which resolve in 404 as no logo has been selected yet).
 
I didn't get this. This much I understood that logo will be selected in logoi repo then we can update it, so for now we should use, what you recommended.
"Resolve in 404" please explain a bit.
>I don't know if we should show that the image is missing, or [hide it when missing](https://www.geeksforgeeks.org/how-to-hide-image-not-found-icon-when-source-image-is-not-found/)

Hide it when missing seems apt, look wise. There's no point of displaying an icon, when it's missing.

**Comment by bryan-brancotte** [comment]
> which resolve in 404
I mean that the image is not found, when you click on the link you will get an [HTTP code 404](https://en.wikipedia.org/wiki/HTTP_404)

I did not follow precisely for the logo, I assumed that it will one day appear at  https://github.com/edamontology/edamontology/raw/main/EDAMrelations.png and want the browser to be ready to automatically use it.

**Comment by raashika03** [comment]
OK means that I should just change the address of the image.
