### ISSUE TITLE
Configurable communi logos for browser not ontology

### ISSUE THREAD

**Issue by raashika03** [edamontology/edam-browser#77]
I agree with @hmenager, that it'll be good to merge the current version now 👍🏽

And creating separate issues for:
- making this configurable in https://github.com/edamontology/edamontology/blob/main/EDAM_dev.owl
- extending with more links/info (_e.g._ license, ...)
- putting it into some kind of _About_ menu|"splashscreen" (perhaps in addition to having these main logoi - gh, gitter, twitter - somewhere in the footer as _"Follow or ask for help at ..."_)

Removing "draft" and "WIP", should we proceed towards merge now?

_Originally posted by @matuskalas in https://github.com/edamontology/edam-browser/issues/62#issuecomment-812846395_

**Comment by raashika03** [comment]
I'll look for ways to implement this for sure @matuskalas @hmenager.
Documenting it here in the form of issue, so that I won't miss it anyhow after that initial PR will be merged :D

**Comment by raashika03** [comment]
Let #96 Be merged @matuskalas @hmenager then I'll take up this issue in full fledged. Something like this I've thought to do as per what you suggested 
![IMG_20210411_060012](https://user-images.githubusercontent.com/45493793/114288230-47c29c00-9a8b-11eb-9d6b-9e86c23f16ca.jpg)
![IMG_20210411_060031](https://user-images.githubusercontent.com/45493793/114288231-51e49a80-9a8b-11eb-841d-7d49d975e15e.jpg)

**Comment by raashika03** [comment]
FAQ section can also be covered in this menu, if later on its needed.

**Comment by raashika03** [comment]
Hi @hmenager @matuskalas I came up with two ideas for the menu to be kept in the footer portion:
1) this seems ok if some menu or splashscreen kind of thing isn't gonna created. And since we don't have so many things to be kept in that menu so this seems ok.
![Screenshot from 2021-04-13 05-39-41](https://user-images.githubusercontent.com/45493793/114477999-f0533600-9c1a-11eb-9a2f-2b04a4ba35fa.png)
2) this sounds nice if we've so many things to be included in the menu then at the place of that copyright thing we can create some menu which will have all those options as we discussed.
![Screenshot from 2021-04-13 05-40-59](https://user-images.githubusercontent.com/45493793/114478008-f47f5380-9c1a-11eb-840f-015f0a3d6b1a.png)

Which one do you like the most?
Here I'm attaching some template can you share your views if you like some other more. [template](https://www.web-eau.net/blog/10-best-footer-html-css-snippets)


And that theme option as I told above I'wont include in this. Earlier I thought this menu was had to be created in the Header section. (I missed footer in the proposed ideas, somehow :( )

**Comment by raashika03** [comment]
![Screenshot from 2021-04-13 06-51-47](https://user-images.githubusercontent.com/45493793/114482867-ec2c1600-9c24-11eb-9705-4233ef75a68e.png)
this format also looks nice.

**Comment by bryan-brancotte** [comment]
Having configurable communi links (and logo why not) can be very usefull when considering that a instance of the browser could be setup for https://github.com/edamontology/edam-bioimaging

**Comment by bryan-brancotte** [comment]
We should first update https://github.com/edamontology/edam2json/ in order to add in the export le various information that will be added to the owl file
