### ISSUE TITLE
Enhancement of UI of dropdown menu!

### ISSUE THREAD

**Issue by secrashi** [edamontology/edam-browser#83]
Current: In the dropdown menu, on hovering over the items of the list, the text cursor shows up.

![IMG_20210405_100725](https://user-images.githubusercontent.com/56053777/113538034-d9e42380-95f7-11eb-8959-a950bf2c0352.jpg)

Enhancement: Instead of a text cursor, a pointer would enhance its UI.

**Comment by raashika03** [comment]
This sounds good and reasonable, you should directly create a PR for this, this will be merged by the mentors without any suggestions ig.

**Comment by secrashi** [comment]
> This sounds good and reasonable, you should directly create a PR for this, this will be merged by the mentors without any suggestions ig.

Yeah, sure!
