### ISSUE TITLE
Making the UI of subsection in details component more responsive!

### ISSUE THREAD

**Issue by secrashi** [edamontology/edam-browser#84]
**Problem:** The characters of the text split when the tab is resized.

![IMG_20210405_102015](https://user-images.githubusercontent.com/56053777/113538577-3136c380-95f9-11eb-810d-fc7c0830be91.jpg)

**Proposed Solution:** On resizing, words get split instead of characters. For example, instead of _devel_ in one line and _opment_ in the other, the whole world development gets shifted to another line.

**Comment by raashika03** [comment]
This's a pretty good idea, same suggestion as #83 (to create PR directly). Create issues only for those features for which you think that might get so many suggestions or won't be merged either. Otherwise creating PR directly fastens up the process of merging and solving issues [saying this from my experience :smile:  ].

**Comment by secrashi** [comment]
> This's a pretty good idea, same suggestion as #83 (to create PR directly). Create issues only for those features for which you think that might get so many suggestions or won't be merged either. Otherwise creating PR directly fastens up the process of merging and solving issues [saying this from my experience 😄 ].

Ohh, I made an issue first to keep a track of all the changes I was proposing but I'll take care of this from next time. Thanks for letting me know!

**Comment by raashika03** [comment]
Can be closed @bryan-brancotte by #101

**Comment by raashika03** [comment]
@bryan-brancotte can be closed via #101

**Comment by secrashi** [comment]
Closing with #101
