### ISSUE TITLE
Change tree nodes cursor shape

### ISSUE THREAD

**Issue by HagerDakroury** [edamontology/edam-browser#90]
**Slightly Related to** #83 

**Issue Description:** 
Whenever the cursor moves to the text of the nodes, a text cursor appears (even though the text is not selectable). The expected behaviour of that cursor is selecting the text but the current behaviour is selecting and expanding the nodes

![cursorTree](https://user-images.githubusercontent.com/37930475/113714851-22c7d500-96e9-11eb-8643-55b750f49a7b.gif)

**Proposed Solution:**
Change the cursor to a pointer cursor like suggested in #83 or enable selecting text.

**Comment by matuskalas** [comment]
I fully agree! Although I'm not so sure which of the 2 options is better, would like to hear from @bryan-brancotte and @hmenager

One option I'm considering is:
- Text selection enabled on the text
- Expansion/collapsing near the "circle" node (that area would have to be big enough), or also on the text if it's just a click without dragging/_etc._
- I personally like the graphical appearance of the full/empty circle nodes, but it might be a bit non-intuitive to users used to other ontology browser which show "+"/"-" on expandable nodes (_e.g._ [BioPortal](https://bioportal.bioontology.org/ontologies/EDAM/?p=classes)(seems to be down at the moment) or [OLS](https://www.ebi.ac.uk/ols/ontologies/edam)). Could we consider adding that, somehow without destroying the neat design? (This is of course a separate issue, needing some graphical suggestions)

**Comment by HagerDakroury** [comment]
> 
> * Text selection enabled on the text

Although text selection would kind of defy the purpose of SVG, it can be a solution if needed. (I think it's enabled anyways when selecting outside the tree)
![image](https://user-images.githubusercontent.com/37930475/114165131-678f7e00-992c-11eb-8c65-058a39f2dc40.png)


> * I personally like the graphical appearance of the full/empty circle nodes, but it might be a bit non-intuitive to users used to other ontology browser which show "+"/"-" on expandable nodes (_e.g._ [BioPortal](https://bioportal.bioontology.org/ontologies/EDAM/?p=classes) or [OLS](https://www.ebi.ac.uk/ols/ontologies/edam)). Could we consider adding that, somehow without destroying the neat design? (This is of course a separate issue, needing some graphical suggestions)

I agree! the visualization makes the browser stand out and looks nice and usable.

Maybe just stick with changing the cursor shape for now? if text selection is not an absolute need

**Comment by bryan-brancotte** [comment]
Hi

I don't think text selection is needed as when we click on a node it is presented on the right where text can be selected, also enabling text selection will prevent expending the node on click and we would lose something on that. I would definitely goes for changing the cursor and nothing else.

**Comment by HagerDakroury** [comment]
> Hi
> 
> I don't think text selection is needed as when we click on a node it is presented on the right where text can be selected, also enabling text selection will prevent expending the node on click and we would lose something on that. I would definitely goes for changing the cursor and nothing else.

Agreed!
